//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSOP.SlideShow {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TSOP.SlideShow.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following duplicate images were not added:.
        /// </summary>
        internal static string DUPLICATE_IMAGES_NOT_ADDED {
            get {
                return ResourceManager.GetString("DUPLICATE_IMAGES_NOT_ADDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No images are selected.
        /// </summary>
        internal static string IMAGES_NONE_SELECTED {
            get {
                return ResourceManager.GetString("IMAGES_NONE_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Point Syntax.
        /// </summary>
        internal static string INVALID_POINT_SYNTAX {
            get {
                return ResourceManager.GetString("INVALID_POINT_SYNTAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Scale Factor.
        /// </summary>
        internal static string INVALID_SCALE_FACTOR {
            get {
                return ResourceManager.GetString("INVALID_SCALE_FACTOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load slideshow data.
        /// </summary>
        internal static string LOAD_SLIDESHOW_FAILED {
            get {
                return ResourceManager.GetString("LOAD_SLIDESHOW_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Confirm.
        /// </summary>
        internal static string MESSAGE_BOX_TITLE_CONFIRM {
            get {
                return ResourceManager.GetString("MESSAGE_BOX_TITLE_CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string MESSAGE_BOX_TITLE_ERROR {
            get {
                return ResourceManager.GetString("MESSAGE_BOX_TITLE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        internal static string MESSAGE_BOX_TITLE_INFO {
            get {
                return ResourceManager.GetString("MESSAGE_BOX_TITLE_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string MESSAGE_BOX_TITLE_WARNING {
            get {
                return ResourceManager.GetString("MESSAGE_BOX_TITLE_WARNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value exceeds allowed limits of a point.
        /// </summary>
        internal static string POINT_OUT_OF_RANGE {
            get {
                return ResourceManager.GetString("POINT_OUT_OF_RANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value exceeds allowed range of scale factor.
        /// </summary>
        internal static string SCALE_FACTOR_OUT_OF_RANGE {
            get {
                return ResourceManager.GetString("SCALE_FACTOR_OUT_OF_RANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error deleting the script file.
        /// </summary>
        internal static string SCRIPT_DELETE_FAILED {
            get {
                return ResourceManager.GetString("SCRIPT_DELETE_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script file delete.
        /// </summary>
        internal static string SCRIPT_DELETE_SUCCEEDED {
            get {
                return ResourceManager.GetString("SCRIPT_DELETE_SUCCEEDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The script is empty.
        /// </summary>
        internal static string SCRIPT_EMPTY {
            get {
                return ResourceManager.GetString("SCRIPT_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error loading the script file.
        /// </summary>
        internal static string SCRIPT_LOAD_FAILED {
            get {
                return ResourceManager.GetString("SCRIPT_LOAD_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script file loaded.
        /// </summary>
        internal static string SCRIPT_LOAD_SUCCEEDED {
            get {
                return ResourceManager.GetString("SCRIPT_LOAD_SUCCEEDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a single script.
        /// </summary>
        internal static string SCRIPT_MULTI_SELECTED {
            get {
                return ResourceManager.GetString("SCRIPT_MULTI_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A script must be selected.
        /// </summary>
        internal static string SCRIPT_NOT_SELECTED {
            get {
                return ResourceManager.GetString("SCRIPT_NOT_SELECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error saving the script file.
        /// </summary>
        internal static string SCRIPT_SAVE_FAILED {
            get {
                return ResourceManager.GetString("SCRIPT_SAVE_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Script fie saved.
        /// </summary>
        internal static string SCRIPT_SAVE_SUCCEEDED {
            get {
                return ResourceManager.GetString("SCRIPT_SAVE_SUCCEEDED", resourceCulture);
            }
        }
    }
}
